---
title: "EDA3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)
library(datetime)
library(lubridate)
library(dplyr)
library(reshape2)
```

## uniform warehouse dataset

```{r}
df <- read.csv("warehouse_credit_cleansed.csv", header = T)
df <- arrange(df, WAREHOUSE_NAME)
```

```{r}
##efficiency=execution/actual
#df$efficiency <- round(df$EXECUTION_CREDITS/df$ACTUAL_CREDITS,3)
```


```{r}
# create new ID
ids <-distinct(data.frame(df$WAREHOUSE_NAME)) %>% rename(WAREHOUSE_NAME =  df.WAREHOUSE_NAME )
ID_CROSSWALK <- ids %>% mutate( NEWID = row_number()) 
df <- full_join(df,ID_CROSSWALK, by ="WAREHOUSE_NAME")
df <- df[,c("NEWID","WAREHOUSE_METERING_START_TIME", "ACTUAL_CREDITS", "EXECUTION_CREDITS", "EFFECTIVE_EXECUTION_CREDITS")]
df <- arrange(df, NEWID, WAREHOUSE_METERING_START_TIME)

# wipe out duplicated data
dup.no <- which(duplicated(df[, c("NEWID","WAREHOUSE_METERING_START_TIME")]))
dup.list <- df[, c("NEWID","WAREHOUSE_METERING_START_TIME")][dup.no, ]

dup.check <- data.frame(matrix(nrow = 0 , ncol = 6)) 
colnames(dup.check ) <- colnames(df)
for(i in 1:length(dup.list$NEWID)){
  dup.check <- rbind(dup.check, filter(df, NEWID == dup.list$NEWID[i] & WAREHOUSE_METERING_START_TIME == dup.list$WAREHOUSE_METERING_START_TIME[i]))
}
df <- df[-dup.no, ]

 #  df1$WAREHOUSE_METERING_START_TIME <- as.character(as_datetime(df1$WAREHOUSE_METERING_START_TIME))
 # arrange(count(df, NEWID), desc(n))
# dup.list = data.frame(matrix(, nrow = 0, ncol = 2))
# for(i in 1: dim(dup.check)[1]){
#   # i = 1
#   dup.list = rbind(filter(ID_CROSSWALK, NEWID == dup.check$NEWID[i]), dup.list)
# }
# dup.list <- distinct(dup.list)

#######  currently not run
# create the complete time line from 2019/08/01/00:00:00 to 2021/08/02/05:00:00
# out <- ISOdatetime(2019,07,31,20,0,0) + (0:17573) *60*60
# attr(out, "tzone") <- "UTC" 
# time_index <- as.character(out)
# time_index[17574]
# # cast ACTUAL, EXECUTION, EFFECTIVE EXECUTION CREDITS of 'df' onto created time index
# df_actual <- dcast(df, NEWID ~ WAREHOUSE_METERING_START_TIME, value.var = "ACTUAL_CREDITS")
# df_execution <- dcast(df, NEWID ~ WAREHOUSE_METERING_START_TIME, value.var = "EXECUTION_CREDITS")
# df_effective_execution <- dcast(df, NEWID ~ WAREHOUSE_METERING_START_TIME, value.var = "EFFECTIVE_EXECUTION_CREDITS")
# 
# ##########
# add_time <- function(df, timeline){
#   # df <- df_actual
#   # timeline <- time_index
#   output <- data.frame(matrix(, nrow = dim(df)[1], ncol = length(timeline)))
#   colnames(output) <- timeline
#   for (j in 1: length(timeline)) {
#     if(is.element(timeline[j], colnames(df))){
#        output[, j] <- df[, match(timeline[j], colnames(df))]
#     }else{
#       output[, j] <- output[, j]
#     }
#   }
#   output <- cbind(NEWID = df[, c("NEWID")], output)
#   return(output)
# }
# ###
# subset(df_actual, NEWID == 283)
# df_actual <- add_time(df_actual, timeline = time_index)
# df_execution <- add_time(df_execution, timeline = time_index)
# df_effective_execution <- add_time(df_effective_execution, timeline = time_index)
```


## deal with day/week/month
```{r}
library(data.table)
df$year <- year(df$WAREHOUSE_METERING_START_TIME)
df$month <- month(df$WAREHOUSE_METERING_START_TIME)
df$week <- week(df$WAREHOUSE_METERING_START_TIME)
df$day <- yday(df$WAREHOUSE_METERING_START_TIME)
# df$year<- as.character(df$year)
# df$month <- as.character(df$month)
# df$week <- as.character(df$week)
# df$day <-  as.character(df$day)

## creat day unit dataset
df_day <- df %>%
  group_by(NEWID,year,day) %>%
  summarise(ACTUAL_CREDITS=sum(ACTUAL_CREDITS),EXECUTION_CREDITS=sum(EXECUTION_CREDITS),averageEfficiency=EXECUTION_CREDITS/ACTUAL_CREDITS)

#error <- filter(df_day,averageEfficiency=="Inf")
df_day <- df_day[!(df_day$averageEfficiency=="Inf"),]


# a <- filter(df, df$NEWID=="1" & df$year=="2021" & df$day=="174")
# mean(a$efficiency)
# filter(df_day,df_day$NEWID=="34" & df_day$year=="2019" & df_day$day=="319")

### then we have a dataset, every warehouse's efficiency in one day.

df_week <- df %>%
  group_by(NEWID,year,week) %>%
  summarise(ACTUAL_CREDITS=sum(ACTUAL_CREDITS),EXECUTION_CREDITS=sum(EXECUTION_CREDITS),averageEfficiency=EXECUTION_CREDITS/ACTUAL_CREDITS)

df_week <- df_week[!(df_week$averageEfficiency=="Inf"),]

## 
df_month <- df %>%
  group_by(NEWID,year,month) %>%
  summarise(ACTUAL_CREDITS=sum(ACTUAL_CREDITS),EXECUTION_CREDITS=sum(EXECUTION_CREDITS),averageEfficiency=EXECUTION_CREDITS/ACTUAL_CREDITS)

df_month <- df_month[!(df_month$averageEfficiency=="Inf"),]
```

## group warehouse into three level efficiency
```{r}
df_day <- arrange(df_day,year,day)
df_day <- df_day %>%
  group_by(year,day) %>%
  mutate(flag= case_when(
    averageEfficiency <0.025 ~ "C",
    averageEfficiency >= 0.025 &averageEfficiency<0.5 ~"B",
    averageEfficiency >= 0.5 ~"A"
  ))

## for weekly data
df_week <- arrange(df_week,year,week)
summary(df_week$averageEfficiency)
# 0.025, 0.5
df_week <- df_week %>%
  group_by(year,week) %>%
  mutate(flag= case_when(
    averageEfficiency <0.025 ~ "C",
    averageEfficiency >= 0.025 &averageEfficiency<0.5 ~"B",
    averageEfficiency >= 0.5 ~"A"
  ))
#write_csv(df_week,file = "~/Desktop/df_week.csv")

df_month <- arrange(df_month,year,month)
df_month <- df_month %>%
  group_by(year,month) %>%
  mutate(flag= case_when(
    averageEfficiency <0.025 ~ "C",
    averageEfficiency >= 0.025 &averageEfficiency<0.5 ~"B",
    averageEfficiency >= 0.5 ~"A"
  ))
```

## rolling weekly
```{r}
#create data frame with 0 rows and 5 columns
result <- data.frame(matrix(ncol = 5, nrow = 0))

#provide column names
colnames(result) <- c('year', 'week', 'bestAvgEfi', "midAvgEfi","worstAvgEfi")

for (y in 2019:2021){
  a <- filter(df_week, year==y)
 for (i in 1:52){
   # i <- 53
       a1 <- filter(a,flag =="A" & week==i)
       ID1 <- a1$NEWID
       m <- i+1
       aA <- filter(a,week==m)
       aA1 <- aA[aA$NEWID %in% ID1,]
      bestAvgEfi=mean(aA1$averageEfficiency)
      
       a2 <- filter(a,flag =="B" & week==i)
       ID2 <- a2$NEWID
       aB <- filter(a,week==m)
       aB1 <- aB[aB$NEWID %in% ID2,]
      midAvgEfi=mean(aB1$averageEfficiency)
      
       a3 <- filter(a,flag =="C" & week==i)
       ID3 <- a3$NEWID
       aC <- filter(a,week==m)
       aC1 <- aC[aC$NEWID %in% ID3,]
      worstAvgEfi=mean(aC1$averageEfficiency)
      
       result[nrow(result) + 1,] = c(y, i, bestAvgEfi,midAvgEfi,worstAvgEfi)
       } 
}

```


## plot
```{r}
result_clean <- result[!(result$bestAvgEfi=="NaN"&result$midAvgEfi=="NaN"&result$worstAvgEfi=="NaN"),]
result_clean$date <- paste(result_clean$year,result_clean$week)

#test <- result_clean[50:60,]
ggplot(result_clean)+
  geom_point(aes(x=date,y=bestAvgEfi))+
  geom_point(aes(x=date,y=midAvgEfi),col="blue")+
  geom_point(aes(x=date,y=worstAvgEfi),col="red")+
  labs(x="weekly",y="effiency")+
  scale_color_manual(name = "weekly efficiency", values = c("bestAvgEfi" = "dark", "midAvgEfi" = "blue","worstAvgEfi" = "red"))



```

## rolling monthly
```{r}
#create data frame with 0 rows and 5 columns
resultMonth <- data.frame(matrix(ncol = 5, nrow = 0))

#provide column names
colnames(resultMonth) <- c('year', 'month', 'bestAvgEfi', "midAvgEfi","worstAvgEfi")

for (y in 2019:2021){
  b <- filter(df_month, year==y)
 for (i in 1:11){
       b1 <- filter(b,flag =="A" & month==i)
       bID1 <- b1$NEWID
       m <- i+1
       bA <- filter(b,month==m)
       bA1 <- bA[bA$NEWID %in% bID1,]
      bestAvgEfi=mean(bA1$averageEfficiency)
      
       b2 <- filter(b,flag =="B" & month==i)
       bID2 <- b2$NEWID
       bB <- filter(b,month==m)
       bB1 <- bB[bB$NEWID %in% bID2,]
      midAvgEfi=mean(bB1$averageEfficiency)
      
       b3 <- filter(b,flag =="C" & month==i)
       bID3 <- b3$NEWID
       bC <- filter(b,month==m)
       bC1 <- bC[bC$NEWID %in% bID3,]
      worstAvgEfi=mean(bC1$averageEfficiency)
      
       resultMonth[nrow(resultMonth) + 1,] = c(y, i, bestAvgEfi,midAvgEfi,worstAvgEfi)
       } 
}

## plot
resultMonth_clean <- resultMonth[!(resultMonth$bestAvgEfi=="NaN"&resultMonth$midAvgEfi=="NaN"&resultMonth$worstAvgEfi=="NaN"),]
resultMonth_clean$date <- paste(resultMonth_clean$year,resultMonth_clean$month)

ggplot(resultMonth_clean)+
  geom_point(aes(x=date,y=bestAvgEfi))+
  geom_point(aes(x=date,y=midAvgEfi),col="blue")+
  geom_point(aes(x=date,y=worstAvgEfi),col="red")+
  labs(x="monthly",y="effiency")+
  scale_color_manual(name = "monthly efficiency", values = c("bestAvgEfi" = "dark", "midAvgEfi" = "blue","worstAvgEfi" = "red"))

```


## rolling daily
```{r}
#create data frame with 0 rows and 5 columns
resultDay <- data.frame(matrix(ncol = 5, nrow = 0))

#provide column names
colnames(resultDay) <- c('year', 'day', 'bestAvgEfi', "midAvgEfi","worstAvgEfi")

for (y in 2019:2021){
  d <- filter(df_day, year==y)
 for (i in 1:365){
       d1 <- filter(d,flag =="A" & day==i)
       dID1 <- d1$NEWID
       m <- i+1
       dA <- filter(d,day==m)
       dA1 <- dA[dA$NEWID %in% dID1,]
      bestAvgEfi=mean(dA1$averageEfficiency)
      
       d2 <- filter(d,flag =="B" & day==i)
       dID2 <- d2$NEWID
       dB <- filter(d,day==m)
       dB1 <- dB[dB$NEWID %in% dID2,]
      midAvgEfi=mean(dB1$averageEfficiency)
      
       d3 <- filter(d,flag =="C" & day==i)
       dID3 <- d3$NEWID
       dC <- filter(d,day==m)
       dC1 <- dC[dC$NEWID %in% dID3,]
      worstAvgEfi=mean(dC1$averageEfficiency)
      
       resultDay[nrow(resultDay) + 1,] = c(y, i, bestAvgEfi,midAvgEfi,worstAvgEfi)
       } 
}

## plot
resultDay_clean <- resultDay[!(resultDay$bestAvgEfi=="NaN"&resultDay$midAvgEfi=="NaN"&resultDay$worstAvgEfi=="NaN"),]
resultDay_clean$date <- paste(resultDay_clean$year,resultDay_clean$day)

ggplot(resultDay_clean)+
  geom_point(aes(x=date,y=bestAvgEfi))+
  geom_point(aes(x=date,y=midAvgEfi),col="blue")+
  geom_point(aes(x=date,y=worstAvgEfi),col="red")+
  labs(x="daily",y="effiency")+
  scale_color_manual(name = "daily efficiency", values = c("bestAvgEfi" = "dark", "midAvgEfi" = "blue","worstAvgEfi" = "red"))
```



## construct week lag dataset
```{r}
df_week_lag <- df_week

df_week_lag$averageEfficiencyLag <- rep(NA)

for (i in 1:dim(df_week_lag)[1]){
  id1 <- as.numeric(df_week_lag[i,1])
  year1 <- df_week_lag[i,2]
  week1 <- df_week_lag[i,3]
  week1 <- week1+1
  df_week_lag$averageEfficiencyLag[i] <- filter(df_week_lag,NEWID==id1,year==year1,week==week1)[1,6]
}

df_week_lag$date <- paste(df_week_lag$year,df_week_lag$week)
df_week_lag_clean <- df_week_lag[!(df_week_lag$averageEfficiencyLag=="NA"),]
df_week_lag_clean$averageEfficiencyLag <- as.numeric(df_week_lag_clean$averageEfficiencyLag)

ee <- filter(df_week_lag_clean,flag=="A")
ggplot(ee)+
  geom_point(aes(x=date,y=averageEfficiencyLag,col=NEWID),alpha=0.3)+
  ylim(c(0,2))
```


